# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bx_everyday_contrast_data',
            fields=[
                ('brand_id', models.IntegerField(max_length=20)),
                ('parent_grade_id', models.IntegerField(default=None, max_length=20, null=True)),
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('grade_id', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('include_num_contrast', models.FloatField(max_length=(20, 2))),
                ('arrival_num_contrast', models.FloatField(max_length=(20, 2))),
                ('stay_num_contrast', models.FloatField(max_length=(20, 2))),
                ('arrival_rate_contrast', models.FloatField(max_length=(20, 2))),
                ('stay_rate_contrast', models.FloatField(max_length=(20, 2))),
                ('month_id', models.IntegerField(max_length=20)),
            ],
        ),
    ]
