# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bx_everyday_contrast_data',
            name='brand_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_everyday_contrast_data',
            name='grade_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_everyday_contrast_data',
            name='month_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_everyday_contrast_data',
            name='parent_grade_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
