# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_auto_20190408_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='BxEverydayContrastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('parent_grade_id', models.IntegerField(blank=True, null=True)),
                ('grade_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('include_num_contrast', models.FloatField()),
                ('arrival_num_contrast', models.FloatField()),
                ('stay_num_contrast', models.FloatField()),
                ('arrival_rate_contrast', models.FloatField()),
                ('stay_rate_contrast', models.FloatField()),
                ('month_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bx_everyday_contrast_data',
                'managed': False,
            },
        ),
    ]
